screencaps:
	# 依赖的库需要放在后面：http://stackoverflow.com/a/409402
	bash -lic 'gcc -g -O0 decoding_encoding.c `pkg-config --libs --cflags libavutil libavcodec libavformat libavfilter libswscale` -o /tmp/_ffmpeg'

